language: ruby
rvm:
  - 2.0.0

matrix:
  allow_failures:
    - rvm: rbx-19mode

script:
- bundle exec rspec

# addons:
#    code_climate:
#      repo_token: f0884115cadbe82b33756e38a9cd32d5129304746a17126d6c7da02e7a69910a

notifications:
  email:
    - justin@jgrubbs.net

gemfile:
  - Gemfile


