language: ruby
rvm:
  - 2.0.0

matrix:
  allow_failures:
    - rvm: rbx-19mode

script:
- CODECLIMATE_REPO_TOKEN=dd4351c1e437fe6bb682de8e30eae582e627b4e0959ed3202839ad057af5d4d1 bundle exec rspec

# addons:
#    code_climate:
#      repo_token: dd4351c1e437fe6bb682de8e30eae582e627b4e0959ed3202839ad057af5d4d1 

notifications:
  email:
    - justin@jgrubbs.net

gemfile:
  - Gemfile


